Pull request Juan
lucaspavlov/instrumentacionycontrol pull request #6
Opened 2018-08-30 14:40 UTC by jfdoppler

Limpie la clase para grabar/reproducir
Ordene un poco el codigo pensando en hacer el barrido en frecuencia
Agregue algunas funciones para generar señales

2018-08-30 21:08 UTC, lucaspavlov commented on recorder.py
> +    return 2*vpp*(np.sin(2*np.pi*np.arange(f_sampleo*duracion)*frecuencia/f_sampleo))
Si no me equivoco tiene que ser vpp/2 en lugar de 2*vpp. Además se le puede agregar un offset. Quedaría:
     return vpp/2*(np.sin(2*np.pi*np.arange(f_sampleo*duracion)*frecuencia/f_sampleo)) + offset

2018-08-30 21:09 UTC, lucaspavlov commented on recorder.py
> +    return (np.sign(señal)+minimo+1)/(2*(maximo-minimo))
Acá me parece que tampoco hace lo correcto (o lo intuitivamente correcto según la definición). Para mi debería ser:

    return (maximo-minimo)*(np.sign(señal)/2+1/2)+minimo

2018-08-30 21:55 UTC, lucaspavlov requested changes

2018-08-30 21:55 UTC, lucaspavlov commented on recorder.py
> +    return 2*vpp*(np.sin(2*np.pi*times*frecuencia/f_sampleo)).astype(dtype)
No da el vpp correcto. Y se le podría agregar un offset (sugerencia)

     return vpp/2*(np.sin(2*np.pi*np.arange(f_sampleo*duracion)*frecuencia/f_sampleo)) + offset

2018-08-30 21:55 UTC, lucaspavlov commented on recorder.py
> +    return (np.sign(señal)+minimo+1)/(2*(maximo-minimo))
No da el máximo correcto. Sugerencia:

    return (maximo-minimo)*(np.sign(señal)/2+1/2)+minimo

2018-08-30 21:58 UTC, lucaspavlov commented on recorder.py
> +    return 2*vpp*(np.sin(2*np.pi*times*frecuencia/f_sampleo)).astype(dtype)
Igual para esta parte no tiene sentido lo del offset (por el tema que la placa tiene el pasabanda), lo decía más por si lo usábamos en otra cosa la función seno, pero lo había visto antes de definirla como astype(dtype).

2018-08-31 19:45 UTC, jfdoppler commented on recorder.py
> +    return 2*vpp*(np.sin(2*np.pi*times*frecuencia/f_sampleo)).astype(dtype)
Agregue el offset por las dudas y corregi el vpp

2018-08-31 19:46 UTC, jfdoppler commented on recorder.py
> +    return (np.sign(señal)+minimo+1)/(2*(maximo-minimo))
Tenes razon, corregi con la linea que pusiste

2018-09-01 11:02 UTC, lucaspavlov approved these changes

2018-09-01 11:03 UTC, merged